name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_NODE_VERSION: 20.x

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-lint-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: corepack enable
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn run lint

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 16.x
          - 18.x
          - 20.x
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-test-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Start Jena SPARQL endpoint
        run: .github/workflows/jena.sh start
      - run: corepack enable
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn run build
      - run: yarn run test
      - uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.node-version }}
          parallel: true
      - name: Test the command line tool against Jena SPARQL endpoint
        run: .github/workflows/jena.sh test
      - name: Stop Jena SPARQL endpoint
        run: .github/workflows/jena.sh stop
        if: always()

  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Consolidate test coverage from different jobs
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  webpack:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-webpack-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: corepack enable
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: npx webpack
